### PR TITLE
Milestone3

### PR DESCRIPTION
**Pull request by Stephanie041996**
implemented friendships with 2 rows for mutual friendship.

### CODE REVIEW

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @JulianaOsemeke and @Stephanie041996 
Such a remarkable project you made :+1: ! Awesome README :100: !
Good job with the rspec testing! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed.

##

Kindly work on the suggested changes  👇.

Users got links to this [artcile](https://explainextended.com/2009/03/07/selecting-friends/) and [stackoverflow](https://stackoverflow.com/questions/4219979/sql-best-practice-for-a-friendship-table) discussion as a hint.
- [x] when friendship is confirmed, an additional row with reversed user-friend pair is created

```ruby
# Friendship model

def confirm_friend
  self.update_attributes(confirmed: true)
  Friendship.create!(friend_id: self.user_id,
                  user_id: self.friend_id,
                  confirmed: true)
end
```
### User model
- [x] In order to get all posts written by a user on their friends, students can use the simple method in the User model (in order to NOT do it with Enumerable)
```
# User model
def friends_and_own_posts
  Post.where(user: (self.friends.to_a << self))
  # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
end
```
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad (Code Reviewer)](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Comment by Stephanie041996** [comment]
Thank you. I have implemented the changes

**Comment by umairarshadbutt** [comment]
Hi @Stephanie041996, you can re-submit for re-review.

**Review by george-shammar — APPROVED** [review]
### **STATUS: APPROVED** :heavy_check_mark: :heavy_check_mark: 

Thanks for implementing the requested changes from the previous. :+1: 

Good job :+1: :clap: 

You may proceed to the next milestone.

**Cheers and happy coding.** :smile:

**Pull request merged**
